config/routes.rb
Rails.application.routes.draw do
  resources :order_details
  resources :orders
  resources :customers
  resources :categories
  root "orders#index"
  resources :menus
  get "report", to: "report#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy
  accepts_nested_attributes_for :order_details, allow_destroy: :true

  before_save :set_total

  validates :status, inclusion: %w(NEW PAID CANCELLED)
  validates :customer_id, presence: true
  validates :date, presence: true
  validates_associated :order_details

  def total 
    order_details.collect { |order_detail| order_detail.valid? ? order_detail.unit_price * order_detail.quantity : 0 }.sum
  end

  private
  def set_total
    self[:total] = total
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: %i[ show edit update destroy ]
  skip_before_action :verify_authenticity_token


  # GET /orders or /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1 or /orders/1.json
  def show
    @items =  @order.order_details
  end

  # GET /orders/new
  def new
    @order = Order.new
    @menus = Menu.all
    @order.order_details.new
  end

  # GET /orders/1/edit
  def edit
    @menus = Menu.all
  end

  # POST /orders or /orders.json
  def create
    @menus = Menu.all
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to order_url(@order), notice: "Order was successfully created." }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1 or /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to order_url(@order), notice: "Order was successfully updated." }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1 or /orders/1.json
  def destroy
    @order.destroy
    
    respond_to do |format|
      format.html { redirect_to orders_url, notice: "Order was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def order_params
      params.require(:order).permit(:date, :status, :customer_id, order_details_attributes: [:id, :menu_id, :unit_price, :quantity].push(:_destroy))
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_with(model: order) do |form| %>
  <% if order.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
        <% order.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :date, style: "display: block" %>
    <%= form.date_field :date %>
  </div>

  <div class="form-group">
    <%= form.label :status, style: "display: block" %>
    <%= form.select :status, options_for_select(["NEW", "PAID", "CANCELLED"]), :class => 'genForm_dropBox' %>
  </div>

  <div class="form-group">
    <%= form.label :Customer, style: "display: block" %>
    <%= form.collection_select :customer_id, Customer.order(:email), :id, :email, {}, {class: 'select2'} %>
  </div>

  <strong>Both item and price is in the same order</strong>

  <table class="table" id="menus">
  <tr>
    <th>Item</th>
    <th>Price</th>
    <th>Quantity</th>
  </tr>
  <tbody class="order_details">
        <%= form.fields_for :order_details do |f| %>
          <%= render 'order_detail_fields', f: f %>
        <% end %>
  </tbody>
</table>
  <div>
    <%= link_to_add_association 'Add item', form, :order_details, data: {association_insertion_node: '.order_details', association_insertion_method: :append} %>
    <%= form.submit %>
  </div>
<% end %>

app/views/orders/_order_detail_fields.html.erb
<tr class="nested-fields">
  <td>
    <%= f.collection_select :menu_id, Menu.order(:id), :id, :item_name, {} %>
  </td>
  <%= f.hidden_field :unit_price, :value => @price %> 
  <td>
  <%= f.collection_select :unit_price, Menu.order(:id), :price, :price, {} %>
  </td>
  <td>
  <%= f.number_field :quantity, :min => 0 %> 
  </td>
  <td>
    <%= link_to_remove_association "remove item", f, class: 'btn btn-primary' %>
  </td>
</tr>

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render "form", order: @order, menus: @menus %>

<br>

<div>
  <%= link_to "Show this order", @order %> |
  <%= link_to "Back to orders", orders_path %>
</div>

app/views/orders/index.html.erb
<body>
  <p style="color: green"><%= notice %></p>
  
  <h1>Orders</h1>
  <p><%= link_to "Menus", menus_path %></p> 
  <p><%= link_to "Customers", customers_path %></p>
  <p><%= link_to "Report", report_path %></p>

  <table class="table">
    <thead>
      <tr>
        <th scope="col">Date</th>
        <th scope="col">Status</th>
        <th scope="col">Email</th>
        <th scope="col">Total</th>
      </tr>
    </thead>
    <tbody id="orders">
      
      <% @orders.each do |order| %>
        <tr>
          <td><%= order.date %></td>
          <td><%= order.status %></td>
          <td><%= order.customer.email %></td>
          <td><%= order.total %></td>
          <td><%= link_to "Show this order", order %></td>
      </tr>
    <% end %>
    </tbody>
  </table>

  
  <%= link_to "New order", new_order_path %>
</body>

app/views/orders/new.html.erb
<h1>New order</h1>

<%= render "form", order: @order, menus: @menus %>

<br>

<div>
  <%= link_to "Back to orders", orders_path %>
</div>

app/views/orders/show.html.erb
<p style="color: green"><%= notice %></p>

<div>
  <p>
    <strong>Date:</strong>
    <%= @order.date %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= @order.status %>
  </p>

  <p>
    <strong>Customer:</strong>
    <%= @order.customer.email %>
  </p>

  <p>
    <strong>Total:</strong>
    <%= @order.total %>
  </p>

</div>

<table class="table" id="menus">
  <tr>
    <th>Item name</th>
    <th>Price</th>
    <th>Quantity</th>
  </tr>
  <% @items.each do |item| %>
    <% if item.quantity != 0 %>
    <tr>
      <td><%= item.menu.item_name %></td>
      <td><%= item.unit_price %></td>
      <td><%= item.quantity %></td>
    </tr>
    <% end %>
  <% end %>
</table>

<div>
  <%= link_to "Edit this order", edit_order_path(@order) %> |
  <%= link_to "Back to orders", orders_path %>

  <%= button_to "Destroy this order", @order, method: :delete %>
</div>